server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scentorydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mappers/**/*.xml


